config/routes.rb
Rails.application.routes.draw do
  root 'main#login'
  post 'login_', to: :login, controller: 'main'
  get 'logout', to: :logout, controller: 'main'
  get 'report', to: :report, controller: 'main'
  resources :sf_cases
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/api_connect.rb
class APIConnect
  include ActiveModel::Model
  attr_accessor :user, :password
  validates :api_key, :api_secret, presence: true

  # def connect!()
  #   return false unless self.valid?
  #   # Presume some API class... You'd store that authorization somewhere.
  #   API.authorize(self.api_key,self.api_secret)
  # end

  def valid?
    Salesforce.authenticate({user: self.user, password: self.password})
  end
end

app/models/sf_case.rb
class SFCase
  include ActiveModel::Model
  include SalesforceProtocol
  @name = "Case"
  @FIELDS = [:Id, :Subject, :CaseNumber, :Origin, :Status, :Priority, :id]
  attr_accessor(*@FIELDS,)

  class << self
    include SalesforceProtocol
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private

    def require_login
      if !session[:sf_cred]
        flash[:danger] = "Please login"
        redirect_to "/"
      end
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :require_login, :only => [:login, :login_]

  def login
    if session[:sf_cred]
      redirect_to "/sf_cases"
    end
    @connection = APIConnect.new
  end

  def login_
    @connection = APIConnect.new(user_params)
    if @connection.valid?
      session[:sf_cred] = true
      flash[:success] = "Successfully logged in"
      redirect_to "/sf_cases"
    else
      flash[:danger] = "Cannot authenticate!"
      redirect_to "/"
    end
  end

  def logout
    session[:sf_cred] = false
    redirect_to "/"
  end

  def report
      
  end

  private

  def user_params
    params.require(:api_connect).permit(:user, :password)
  end
end

app/controllers/sf_cases_controller.rb
class SfCasesController < ApplicationController
  before_action :set_sf_case, only: [:show, :edit, :update, :destroy]

  # GET /sf_cases
  # GET /sf_cases.json
  def index
      @sf_cases = SFCase.all
  end

  # GET /sf_cases/1
  # GET /sf_cases/1.json
  def show
  end

  # GET /sf_cases/new
  def new
    @sf_case = SFCase.new
  end

  # GET /sf_cases/1/edit
  def edit
  end

  # POST /sf_cases
  # POST /sf_cases.json
  def create
    @sf_case = SFCase.create(sf_case_params.to_h.symbolize_keys)
    respond_to do |format|
      if @sf_case.sf_valid?
        set_success_flash_message("Case was successfully created.")
        format.html { redirect_to @sf_case}
        format.json { render :show, status: :created, location: @sf_case.Id }
      else
        set_flash_error_message
        format.html { render :new }
        format.json { render json: @sf_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sf_cases/1
  # PATCH/PUT /sf_cases/1.json
  def update
    h = sf_case_params.to_h
    h[:Id] = params[:id]
    @sf_case = SFCase.update(h.symbolize_keys)

    respond_to do |format|
      if @sf_case.sf_valid?
        set_success_flash_message("Case was successfully updated.")
        format.html { redirect_to sf_case_path(h["Id"])}
        format.json { render :show, status: :ok, location: @sf_case }
      else
        set_flash_error_message
        format.html { redirect_to edit_sf_case_path(@sf_case.Id) }
        format.json { render json: @sf_case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sf_cases/1
  # DELETE /sf_cases/1.json
  def destroy
    SFCase.destroy(params["id"])
    respond_to do |format|
      set_success_flash_message("Case was successfully destroyed.")
      format.html { redirect_to "/sf_cases" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sf_case
      @sf_case = SFCase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sf_case_params
      params.require(:sf_case).permit(SFCase.attributes)
    end

    def set_flash_error_message
      flash[:danger] = @sf_case.errors.messages
    end

    def set_success_flash_message(message)
      flash[:success] = message
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_login?
    session[:sf_cred]
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sf_cases_helper.rb
module SfCasesHelper
  def case_form_path(case_)
    case_.Id ? sf_case_path : new_sf_case_path
  end

  def case_form_method(case_)
    case_.Id ? "put" : "post"
  end

  def case_form_btn_label(case_)
    case_.Id ? "Update" : "Create"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalesforceConnect</title>
    <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded navbar-default">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">SalesforceConnect</a>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/report">説明ーExplanation</a></li>
          <li><a href="/sf_cases">Cases</a></li>
          <%- unless is_login? %>
            <li><a href="/"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <%- else %>
            <li><a href="<%= logout_path %>"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/main/login.html.erb
<div id="sign-in-form-container">
 <div class="container">
   <div class="row">
     <div class="col-md-4 col-md-offset-4 card card-block">
      <%= simple_form_for(@connection, url: "/login_", html: { class: "form-horizontal"}) do |f| %>
        <%= f.input :user, as: :string, placeholder: "", label: "Email" %>
        <%= f.input :password, as: :password, placeholder: "", label: "Password" %>
        <div class="form-group">
          <%= f.button :submit, "Login" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/main/report.html.erb
<div class="panel panel-default">
    <div class="panel-heading">アプリの説明ーSystem Explained</div>
    <div class="panel-body">
      <p>
      CRUDの画面とControllerの機能を作成しました。
      DDDのコンセプト少し利用しました。よく見たら「lib」のフォルダにシステム的なコーディングが含まれています。
      RubyコミュニティーはよくTDDのアプローチを利用しますが今回はこの小さなプロジェクトで使用しませんでした。
      Salesforceオブジェクトをもっと簡単にシステムに結合できるようにモジュール「SalesforceProtocol」を作りました。それともデータベースを追加したい時、
      コーディングをあんまり触れずに簡単にできます。

      このアプリを楽しんで下さい！
      </p>
      <p>
      I have implemented the pages and included the CRUD required functions.
      You will notice that I tried to follow more of the DDD concept.
      I know that the ruby community is more inclined to follow TDD approach, but for this small
      project I decided to ignore it. I have also built a module which will allow alot of flexibility in implementing
      salesforce object more easily into the system. It just a matter of adding the SalesforceProtocol class to the new model object.
      Also adding a database will be very simple it will just be like adding an extra service to the app.

      I hope that this little app pleases you!
      </p>
    </div>
</div>

app/views/sf_cases/_form.html.erb
<%= simple_form_for @sf_case, :url => case_form_path(@sf_case), :method => case_form_method(@sf_case) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :Subject %>
    <%= f.input :Status %>
    <%= f.input :Origin %>
    <%= f.input :Priority %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, (@sf_case.Id ? "Update" : "Create")%>
  </div>
<% end %>

app/views/sf_cases/edit.html.erb
<h1>Modify Case-<%= @sf_case.CaseNumber%></h1>

<%= render 'form', sf_case: @sf_case %>

<%= link_to 'Back ', sf_case_path(@sf_case.Id) %>

app/views/sf_cases/index.html.erb
<a class="btn btn-success btn-sm" href="<%= new_sf_case_path %>">New Case</a>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Subject</th>
      <th>CaseNumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sf_cases.each do |sf_case| %>
      <tr>
        <td><%= sf_case["Id"] %></td>
        <td><%= sf_case["Subject"] %></td>
        <td><%= sf_case["CaseNumber"] %></td>
        <td>
          <%= link_to sf_case_path(sf_case.Id), :class => "btn btn-secondary" do %>
            <i class="fa fa-search"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_sf_case_path(sf_case.Id), :class => "btn btn-primary" do %>
            <i class="fa fa-pencil"></i>
          <% end %>
        </td>
        <td>
          <%= link_to "/sf_cases/#{sf_case["Id"]}", method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
            <i class="fa fa-trash-o"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/sf_cases/new.html.erb
<h1>New Case</h1>

<%= render 'form', sf_case: @sf_case %>

<%= link_to 'Back', sf_cases_path %>

app/views/sf_cases/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<h2>Case-<%= @sf_case.CaseNumber %></h2>
<dl class="dl-horizontal">
    <dt>Id</dt>
    <dd><%= @sf_case.Id %></dd>
    <dt>Subject</dt>
    <dd><%= @sf_case.Subject %></dd>
    <dt>Status</dt>
    <dd><%= @sf_case.Status %></dd>
    <dt>Origin</dt>
    <dd><%= @sf_case.Origin %></dd>
    <dt>Priority</dt>
    <dd><%= @sf_case.Priority %></dd>

</dl>

<%= link_to edit_sf_case_path(@sf_case.Id), :class => "btn btn-primary" do %>
  <i class="fa fa-pencil"></i>
<% end %>
<%= link_to "/sf_cases/#{@sf_case.Id}", method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" do %>
          <i class="fa fa-trash-o"></i>
<% end %>
<p>
<%= link_to 'Back ', sf_cases_path %>
</p>